eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: 'http://localhost:4200'
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
            allowed-headers: '*'
            allow-credentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: formation-route
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/formation/**

        - id: theme-formation-route
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/theme-formation/**

        - id: client_post
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/post/**

        - id: client_candidat
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/candidat/**

        - id: client_formateur
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/formateur/**

        - id: client_admin
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/admin/**

        - id: client_role
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/role/**
        - id: client_utilisateur
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/user/**


server:
  port: 8080
